### ISSUE TITLE
Chrome gives a cross site cookie warning in the console.

### ISSUE THREAD

**Issue by Roger-Heathcote** [fac19/week2-hklo#40]
It's not urgent but there will be a breaking change in a future release...

A cookie associated with a cross-site resource at http://giphy.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by oliverjam** [comment]
I've had this on a few of my sites. Unfortunately there's nothing you can do, since the cookie is being set by a 3rd party. It's up to Giphy to fix that, or their cookies will stop working (not the end of the world for us 🙃)
